# Meta Data for SEO

## Homepage
title = "uzERP Support"
titleSeparator = "-"
titleAddition = "Help and Documentation"
description = "uzERP is a suite of business software that delivers big company functionality on a small company budget, including accounting, stock, manufacturing and more."

logo = "images/logo.png"
logo_small = "images/logo.png"

## Open Graph + Twitter Cards
images = ["containers.png"]
twitterSite = "uzerp"
twitterCreator = "uzerp"
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_GB"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-uzerp.png"
schemaTwitter = "https://twitter.com/uzerp"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/uzerpllp"
schemaSection = ""

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "&copy; 2021 uzERP LLP, all rights reserved - powered by <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false
